import { access, readFile, writeFile } from "node:fs/promises";
import type { MemoryEntry } from "../core/schema.js";

const START_MARKER = "<!-- whyanchor:start -->";
const END_MARKER = "<!-- whyanchor:end -->";

function renderEntry(entry: MemoryEntry): string {
  const { title, date, refs, tags, status } = entry.frontmatter;
  const meta: string[] = [date];
  if (refs.length) meta.push(`refs: ${refs.join(", ")}`);
  if (tags.length) meta.push(`tags: ${tags.join(", ")}`);
  const badge = status !== "active" ? ` _(${status})_` : "";
  const firstLine = entry.body.split("\n").find((l) => l.trim().length > 0) ?? "";
  return `- **${title}**${badge} (${meta.join(" · ")})\n  ${firstLine}`;
}

function groupByTag(entries: MemoryEntry[]): Map<string, MemoryEntry[]> {
  const groups = new Map<string, MemoryEntry[]>();
  for (const entry of entries) {
    const tags = entry.frontmatter.tags.length ? entry.frontmatter.tags : ["general"];
    for (const tag of tags) {
      if (!groups.has(tag)) groups.set(tag, []);
      groups.get(tag)!.push(entry);
    }
  }
  return groups;
}

export function renderMemorySection(entries: MemoryEntry[]): string {
  const active = entries.filter((e) => e.frontmatter.status !== "superseded");
  if (active.length === 0) {
    return [START_MARKER, "## Project Memory", "", "_No memory entries yet. Run `whyanchor capture` to add one._", END_MARKER].join(
      "\n"
    );
  }

  const groups = groupByTag(active);
  const lines: string[] = [
    START_MARKER,
    "## Project Memory",
    "",
    "Captured decisions and context for this repo. Generated by `whyanchor generate` — do not edit inside this block, it will be overwritten.",
    "",
  ];

  const sortedTags = [...groups.keys()].sort();
  for (const tag of sortedTags) {
    lines.push(`### ${tag}`, "");
    for (const entry of groups.get(tag)!) {
      lines.push(renderEntry(entry));
    }
    lines.push("");
  }

  lines.push(END_MARKER);
  return lines.join("\n").replace(/\n{3,}/g, "\n\n");
}

export interface UpsertOptions {
  startMarker?: string;
  endMarker?: string;
  /** When the section is new, insert it above this marker line instead of appending. */
  insertBefore?: string;
}

export async function upsertMarkedSection(
  filePath: string,
  section: string,
  options: UpsertOptions = {}
): Promise<"created" | "updated"> {
  const startMarker = options.startMarker ?? START_MARKER;
  const endMarker = options.endMarker ?? END_MARKER;

  let existing = "";
  let created = false;
  try {
    existing = await readFile(filePath, "utf8");
  } catch {
    created = true;
  }

  if (created) {
    await writeFile(filePath, section + "\n", "utf8");
    return "created";
  }

  // Match markers only on lines that consist solely of the marker — an entry's rendered
  // body can legitimately mention "<!-- whyanchor:end -->" as plain text (e.g. an entry
  // documenting this very marker scheme), and a naive indexOf would match that instead of
  // the real closing marker, corrupting the file.
  const lines = existing.split("\n");
  const trimmedLines = lines.map((l) => l.trim());
  const startLine = trimmedLines.indexOf(startMarker);
  const endLine = trimmedLines.lastIndexOf(endMarker);

  let next: string;
  if (startLine !== -1 && endLine !== -1 && endLine >= startLine) {
    const before = lines.slice(0, startLine).join("\n");
    const after = lines.slice(endLine + 1).join("\n");
    next = (before ? before + "\n" : "") + section + (after ? "\n" + after : "\n");
  } else {
    const anchor = options.insertBefore ? trimmedLines.indexOf(options.insertBefore) : -1;
    if (anchor !== -1) {
      const before = lines.slice(0, anchor).join("\n");
      const after = lines.slice(anchor).join("\n");
      next = (before ? before + "\n" : "") + section + "\n\n" + after;
    } else {
      const sep = existing.endsWith("\n") ? "\n" : "\n\n";
      next = existing + sep + section + "\n";
    }
  }

  await writeFile(filePath, next, "utf8");
  return "updated";
}

export async function upsertMemorySection(filePath: string, section: string): Promise<"created" | "updated"> {
  return upsertMarkedSection(filePath, section);
}

export async function fileExists(filePath: string): Promise<boolean> {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}
